version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: mydatabase
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypassword
      REFRESH_SECRET_KEY: nonsense22
      JWT_SECRET_KEY: nonsense
      JWT_SECRET_EXPIRES_IN: 30min
      REFRESH_TOKEN_EXPIRY: 7days
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:15.4
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGSSLMODE: disable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
